### ISSUE TITLE
pytivo seems to drop off tivo list and needs to be restarted

### ISSUE THREAD

**Issue by mickrussom** [wmcbrine/pytivo#24]
I recently upgraded to the latest (as of March 28 2017) and noticed that since December's build with the same conf file the pytivo endpoint drops off the tivo list shortly after content is sent to the tivo. So send a movie, wait about 15 minutes, and pytivo server/endpoint is off the list. needs to be restarted. 

Any suggestions? thanks

**Comment by wmcbrine** [comment]
While that may be the time frame during which you've observed the problem, I don't believe there have been any changes to pyTivo during that time that would have that effect. This has always been flaky, and AFAICT, the fault is on the TiVo side.

But, you could try switching between older and newer versions to see if you can confirm a change in behavior, and in the process, narrow it down to the exact change.
